/**:
  ros__parameters:
    host_ip: "127.0.0.1"
    sensor_ip: "127.0.0.1"
    data_port: 2368
    gnss_port: 10110
    packet_mtu_size: 1500
    launch_hw: true
    setup_sensor: true
    frame_id: tutorial
    diag_span: 1000
    min_range: 0.3
    max_range: 300.0
    cloud_min_angle: 0 
    cloud_max_angle: 360
    scan_phase: 0.0
    sensor_model: TutorialSensor
    calibration_file: $(find-pkg-share nebula_decoders)/calibration/hesai/Pandar128E4X.csv
    rotation_speed: 600
    return_mode: LastStrongest
    retry_hw: false
    dual_return_distance_threshold: 0.1